apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:BTUkR41rtJwPMeL6xa9R3sI=,iv:8R8Tipj2pUTkgric9nWdyi8kTTeWls0EWAZguXoGkUA=,tag:WgV2FwT1aN+1yj4GYfnQpQ==,type:str]
    api-key: ENC[AES256_GCM,data:JT1lBCI/WrGsBFKU8v6RVyyyv6U8YhPjw4gg1qpNepd5qdp3TA==,iv:ATIiBbpJldg0jAJ2DWMQbOgVrCsgMb5jAzR5d7CGbEU=,tag:/vMikJeIqwUUJS4CIwlqHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17k7yuv7n8cxc3pclft8p3dzyjdjcrztpyv746p2g7pkz3j2nr32qphqsxu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVnk0em1vMnNTQjl1YVgx
            RjJEVUd3UjhSWFVJdFFqWXgvMG03c1BISlhZCm5QSWVHRGxHZndhL1RDWVNVdURC
            ejJ3TXE3eDVacnNqMVJMRm5uZks3NUEKLS0tIDlxOXE1aFJLd3g1STY1MDMvSllT
            Uy8rb285TjNGRmRJemRGUEVqQWRGZjQK/i44jew+lJw/ldEJhVSRn59gdMeqxwBo
            3Bf09GgPO8l1P6v4cmmABiXMvp/0zzHAaLNZZE/tbngyjQXHC2PrIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T04:35:42Z"
    mac: ENC[AES256_GCM,data:K8lELSMf0kIoNl6gwiNRHgLG01E1SIVyRNkfMtJ+xy8DyzS6Hwcj6IfNOSW74egrzs5Ml3GK4ftY5VZQDaC2tr8YwV98qWF9GkxOE1PoM+x/rF9XzXkSkMLFOQIGGK78yQv1Ld+TLDEQTwzh/HLr63TWJVLcZW5rLykAVkjoTgg=,iv:la6KNOeq4Yz0LJ8dD/e7IpU9xVKBfhFzTACgA9FGJc4=,tag:qI64cRm/ECZWALyobV/L8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
