apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:8+82luTRB4NabJkDmxTeKi6Rf1WjlRR0lP3a5tPIXp6COJLrsLmxoj5oonKiO1h6fslCa1L0s1Y1fNbN,iv:yqWRAxwT1Omi+hBFIRaTm5gb6r4PXR64c39SyZIpq4Y=,tag:Jy+wo/FmmqWGnMwX5gyIvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17k7yuv7n8cxc3pclft8p3dzyjdjcrztpyv746p2g7pkz3j2nr32qphqsxu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNVY2WDNVdkZCWk5DNVRY
            YWNyVFZWdlhMRmdWS2lKMzd6cGt4Y014Yno4CklQK0FMSHBNd2dTNitOVFNsdTdG
            Ukp6Rlh3bURRU044UHlpWHRKampNTXMKLS0tIHpiK3BvaGRzcG51NnhCUDIraTBk
            YjNnYUlaMXErUTdpOU4vMjdiZXBYdDgKCoJjjd89UykOtnybkrehYXljiFZGxlsW
            4jmUBDGrWE8hqP0Y08LK6vS7Ujk2dn3UjMRkVStX2IKcKANJJFYubA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T04:35:42Z"
    mac: ENC[AES256_GCM,data:BAwyGU0VByjRI4GzDUnYwYO6kg9ieedtaZTOEgFhVUpQeIm1zTOAAxvdDJuumR5DsyPCRfOGi6pD+7J9/Z1fcIGbjZqMblGmZ9YZVRrtYHWOv9p7UwvZsaxp7k7nPkrnxOL7t1ihbJRY/ZVOXGuHO6EKpGJ/iEWrXTNaZW9K9iA=,iv:jKXz1jg7DsfDB3i/6CzoWPqmd8WgrAFHyOpcoXpP3sU=,tag:Esn4YrGPvHlednoyjd2qaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
