apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DLvffLZ+AgQEFVtpGQ==,iv:wOWxXodFuWO8O6wE7knyWPCLFQTPidIm2EyQxSLdEt0=,tag:skLKHW/9z4J5bJG1RWkilg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:SwetRD1oTg/9A4Bc7dkVzTo=,iv:4xXmwon9SKraYjAc9nngZq6FHYmzQBluh7yBEqWJQdA=,tag:tCfkO5f5SoXAen8h3Lt/sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17k7yuv7n8cxc3pclft8p3dzyjdjcrztpyv746p2g7pkz3j2nr32qphqsxu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMS9VS09jL2RJZUFsR25X
            NHpENFFDdVFxQlluRm90ZDZQVlNoSGEvN1hVCnM3TFpNN3FubUpvRTZFM2pIckxy
            NXNyMmhWb3BpSkFxOWcybzU0bjZ6bUUKLS0tIEpaZjViaGdjR25qOHlqelg0S3dp
            ejhlOHZyUUdVclBYSFhkUVZ6bnR5R2MKK+l1Du+cobh8XMfUVmC7U+g1EXC0bbMZ
            XGii8p0BfPbYG7mHVn+ehj4WwCb5j96/Kb/D4HaFzs19tYUE5G/N0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T04:35:42Z"
    mac: ENC[AES256_GCM,data:zZ6QF0ZcwPbnXFIHmgUzjFCBkCzVzXtLnJZAvw3AZjHICmO+w/p0qoTE5Xtk4RA3Mks0PQ/xZwn7Hw5eW5fvjMWKjJBpTxKanlWFVmteduhYMtyGFPxKKs4Oz6ixKE2B8Ry0KuRIwipZuDgCRvobtEaIKjV8GOQeXnXoKp6RC7E=,iv:76RBK14z32UEtnRwzrTq5uSueu+A+9Cp+D51FB+7x+0=,tag:PHWwXHbZkL3s5qCEscY/Ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
