---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "192.168.2.9"
  METALLB_LB_RANGE: "192.168.2.150-192.168.2.200"
  METALLB_K8S_GATEWAY_ADDR: "192.168.2.250"
  METALLB_INGRESS_ADDR: "192.168.2.251"
